### ISSUE TITLE
Release the evaluation code.

### ISSUE THREAD

**Issue by xuweigogogo** [o0Helloworld0o-ustc/ECCV2022_WCPA_track2#2]
About the evaluation code:
Our reproduced version evaluates scores worse than the reported ones.
Hope to see the released version, which will help us improve our performance.
Thanks for your notification.

**Comment by o0Helloworld0o** [comment]
Please see this [link](https://tianchi.aliyun.com/forum/postDetail?spm=5176.12586969.1002.6.729042e0odU1od&postId=383240).
